### PR TITLE
fixation cross

### PR DESCRIPTION
**Pull request by CerenB**
There are couple of changes, all around monitor parameters. In order to set the fixation cross, I've changed how we call the cfg.screen a bit. It was mainly for me to think. I'm fully open to change them/call them with other names. 
InitPTB also changed a bit due to this monitor parameters. As well asl displayInst script, mainly the variables names. 
I'm open to insert fixation cross function into displayInstr if you think that could be good. For now, it has a separated function.

### CODE REVIEW

**Comment by CerenB** [comment]
Lastly, at the moment, behavioral instructions would appear after the this sequence -> 
space4me
wait4trigger ('s' is the key) 
fMRI instructions followed by fixation cross.

**Comment by TomasLenc** [comment]
I just noticed that `Grahn2007_complex.txt` and `Grahn2007_simple.txt` files were removed from `\stim` folder in the previous commit. I thought we were leaving them there becuase they are super small, so they can be easily on github, and we only download the large wav files for training. 

I think it's better to have as much as possible on github so we can keep track of it. Otherwise, you never know retrospectively what was in that dropbx folder that was downloaded and mistakes can happen. 

Could we add these text files back into the git? What do you think?

**Comment by CerenB** [comment]
yes i did not have intention to remove them. I think I tried explaining in previous PR. I didn't know what happened back then. But now I know, I wanted to check the download stim.zip is working or not when I created a mini function for it instead of keeping it in the getParam.m 
And I deleted all the files to see everything works well without path issues. Now I see that in gitignore, that was the problem. 

Yes, as I said before, I completely agree to keep txt files in gitRepo!

**Comment by CerenB** [comment]
but i thought this should do the charm: ```
*.mat
*.tsv

*.txt
!stimuli/Grahn2007_simple.txt
!stimuli/Grahn2007_complex.txt
```

**Comment by CerenB** [comment]
yet the Grahn.txt files are not there.... uuffff

**Comment by CerenB** [comment]
I'm closing this PR since I've made all these changes in separate_fMRI branch and I'll PR that one.

**Pull request closed without merging**
